# Generated by Django 6.0.4 on 2026-04-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('BCV', 'Banco Central de Venezuela'), ('PARALELO', 'Dólar Paralelo'), ('BINANCE', 'Binance P2P')], default='BCV', max_length=50, verbose_name='Fuente de la Tasa')),
                ('value', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Valor de la Tasa')),
                ('fecha_valor', models.DateField(help_text='La fecha dada por la fuente para esta tasa', verbose_name='Fecha Valor Oficial')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Extracción (Scraping)')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='URL de Origen')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Es la tasa activa/actual?')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-fecha_valor', '-fetched_at'],
            },
        ),
    ]
