# Generated by Django 6.0.4 on 2026-04-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcv_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='currency',
            field=models.CharField(default='USD', help_text='Ej: USD, EUR, CNY, TRY, RUB', max_length=10, verbose_name='Moneda'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('source', 'currency', 'fecha_valor')},
        ),
    ]
