# Generated by Django 6.0.4 on 2026-04-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcv_service', '0002_exchangerate_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='value',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Valor de la Tasa'),
        ),
    ]
