# Generated by Django 6.0.4 on 2026-04-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcv_service', '0003_alter_exchangerate_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('INTERES_PRES', 'Interés Prestaciones Sociales'), ('INFLACION', 'Inflación Mensual (INPC)'), ('RESERVAS', 'Reservas Internacionales')], max_length=100, verbose_name='Nombre del Indicador')),
                ('value', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Valor')),
                ('unit', models.CharField(default='%', help_text='Ej: %, USD, Bs.', max_length=20)),
                ('fecha_referencia', models.DateField(verbose_name='Fecha del Dato')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Indicador Económico',
                'verbose_name_plural': 'Indicadores Económicos',
                'ordering': ['-fecha_referencia'],
            },
        ),
    ]
