# Generated by Django 6.0.4 on 2026-04-21 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcv_service', '0004_economicindicator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together=set(),
        ),
    ]
