# Generated by Django 6.0.4 on 2026-04-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcv_service', '0005_alter_exchangerate_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicindicator',
            name='name',
            field=models.CharField(choices=[('INTERES_ACTIVA', 'Tasa de Interés Activa'), ('INTERES_PROM', 'Tasa de Interés Promedio'), ('INFLACION', 'Inflación Mensual (INPC)'), ('RESERVAS', 'Reservas Internacionales')], max_length=100, verbose_name='Nombre del Indicador'),
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='Ruta')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Número de Visitas')),
            ],
            options={
                'verbose_name': 'Estadística de Visita',
                'verbose_name_plural': 'Estadísticas de Visitas',
                'ordering': ['-date', '-count'],
                'unique_together': {('path', 'date')},
            },
        ),
    ]
