# Generated by Django 6.0.4 on 2026-04-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcv_service', '0006_alter_economicindicator_name_pagevisit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagevisit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='visitor_type',
            field=models.CharField(choices=[('WEB', 'Página Web (Humano)'), ('API', 'Consumo API'), ('BOT', 'Bot / Monitor')], default='WEB', max_length=10, verbose_name='Tipo de Visitante'),
        ),
        migrations.AlterUniqueTogether(
            name='pagevisit',
            unique_together={('path', 'date', 'visitor_type')},
        ),
    ]
