# Generated by Django 6.0.4 on 2026-04-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcv_service', '0007_alter_pagevisit_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagevisit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='platform',
            field=models.CharField(choices=[('PC', 'Escritorio'), ('MOBILE', 'Móvil'), ('TABLET', 'Tablet'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=10, verbose_name='Plataforma'),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='referer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Origen (Referer)'),
        ),
        migrations.AlterUniqueTogether(
            name='pagevisit',
            unique_together={('path', 'date', 'visitor_type', 'platform', 'referer')},
        ),
    ]
